### PR TITLE
Update to branch-heads/64

### PR DESCRIPTION
**Pull request by uumaro**
I'm not sure if you want to take this yet or not. In working on cross-compiling support go-webrtc for Windows, I needed to upgrade to branch-heads/64 for [the new cross-compiling support](https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/cIA9fBb9vBE/73cOvZu9BQAJ).

I'm basing my Windows changes on this branch and it works so far, producing a webrtc.lib as well as continuing to be able to build snowflake for mac and linux.

The substantive part of the change is 371aaf6fdc823edb32ba8d2bf55abb9373b4d826; the other commits are just generated headers and libraries. Those are for your reference, and don't necessarily have to be merged as-is. I expect you'll want to generate those yourself anyway. I don't have the hardware to generate libwebrtc-darwin-amd64-magic.a.

### CODE REVIEW

**Comment by arlolra** [comment]
Hmm, I would expect the Linux part of this to be passing in CI, no?
https://travis-ci.org/keroserene/go-webrtc/jobs/360054090

In order to get the macOS build working, I neeeded 99f5639 but the magic is now in 9be426d

For the `include/`s, I did 344fe2a5, which adjust the `.gitignore`

**Comment by uumaro** [comment]
Oh thanks—I didn't think about CI. All the undefined references seem to reference things like `std::string`, `std::__cxx11::basic_string`, `std::__cxx11::basic_ostringstream`, so it looks like the has to do with the use/non-use of the C++11 ABI. I [removed](https://github.com/keroserene/go-webrtc/pull/79/commits/371aaf6fdc823edb32ba8d2bf55abb9373b4d826#diff-6) `-D_GLIBCXX_USE_CXX11_ABI=0` from the .pc files because my build.sh-built libwebrtc-linux-amd64-magic.a automatically used the C++11 ABI. Perhaps the default is different in the CI environment. I can try to build new magic without the C++11 ABI, so it's more compatible with what was there before. (We have long been overriding `-D_GLIBCXX_USE_CXX11_ABI=1` in the Tor Browser build anyway, because it rebuilds the magic and happens to use the C++11 ABI (incompatible with the prepackaged magic).)

Regarding https://github.com/keroserene/go-webrtc/commit/99f5639e0a6c3d368128358dde6226ab9b0cec43, I found the same `-DWEBRTC_MAC=1` change was necessary in the Tor Browser build: https://github.com/uumaro/tor-browser-build/commit/11a5d67379c87731c33d6c2db73a189c2de634b6#diff-0. There, I speculatively also defined `-DWEBRTC_LINUX=1` because I noticed that symbol was also used, though I don't know what its effect is.

Thanks for the .gitignore on include/. I noticed that there were seemingly too many subdirectories, but I didn't know that the correct ones had already been enumerated.

**Comment by arlolra** [comment]
> There, I speculatively also defined -DWEBRTC_LINUX=1 because I noticed that symbol was also used, though I don't know what its effect is.

Ok, I added similar in e45d138

>  I removed -D_GLIBCXX_USE_CXX11_ABI=0 from the .pc files because my build.sh-built libwebrtc-linux-amd64-magic.a automatically used the C++11 ABI. 

I reverted that part since we're still providing a library here with the old ABI.

I briefly tried setting `-D_GLIBCXX_USE_CXX11_ABI=1` in CI but couldn't get it to work.  I think the toolchain is built with `--disable-libstdcxx-dual-abi` so that definition is moot.

See https://github.com/mapbox/mason/issues/157#issuecomment-272378928

**Comment by arlolra** [comment]
> I briefly tried setting -D_GLIBCXX_USE_CXX11_ABI=1 in CI but couldn't get it to work. I think the toolchain is built with --disable-libstdcxx-dual-abi so that definition is moot.

I opened #81 for figuring this out.

The bulk of this is now merged though.  Thanks!

**Pull request closed without merging**
