### PR TITLE
Bump to branch-heads/52

### LINKED ISSUE #39: Play catch up w/ upstream
We shouldn't fall too far behind.

### PR DESCRIPTION
**Pull request by arlolra**
@keroserene you ok with this? Please give it a spin.

Closes #39

### CODE REVIEW

**Comment by keroserene** [comment]
Gave it a spin, works fine locally on my end! But looks like the OSX travis build is complaining:
`==976==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fff5fbfefb1 at pc 0x00000573e1bb bp 0x7fff5fbfef10 sp 0x7fff5fbfe6c0`
at 
` #0 0x573e1ba in wrap_memmove (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x3a1ba)`
Any ideas what might've changed with Xcode/clang at this latest branch head?

**Comment by arlolra** [comment]
Yeah, I've been able to reproduce that on master as well though.  But only on OS X.  So, unrelated to these changes.

I filed https://github.com/golang/go/issues/16150 for it.

**Comment by arlolra** [comment]
Notice it did pass in https://travis-ci.org/keroserene/go-webrtc/builds/139388393, so it seems transient.

**Comment by keroserene** [comment]
:+1:

**Pull request merged**
